name: python workflow 1
 
on:
  push:
    branches:
      - main
  workflow_dispatch:    # run enable run workflow button on github repository to trigger manually
 
jobs:
  python_job1:
    runs-on: self-hosted
    # Whatever mentioned under steps will be performed sequentially
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
 
      - name: setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'    # caching pip dependencies
 
      - name: run python command
        run: python --version
 
      - name: install python required packages
        run: pip install -r requirements.txt

      - name: run test_python.py
        run: pytest
        continue-on-error: true

      - name: check in
        run: echo Hello world

      - run: |
          set -x
          docker version
          docker build -t vishwa800/pydockerimage .

      - name: login into docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_UNAME }}
          password: ${{ secrets.DOCKERHUB_PWORD }}
 
      - name: push docker image into docker hub
        run: docker push vishwa800/pydockerimage
